#!/bin/bash

failure_happened=false
start_time="$(date +%s)"
test_number=0


if [ ! -f "$input" ]; then
  /home/tmr/apache-maven-3.6.3/bin/mvn surefire:test
  exit 0
fi

while read -r line
do
  # execute single test
  /home/tmr/apache-maven-3.6.3/bin/mvn -Dtest="$line" surefire:test -DsuffixName="$test_number"

  # if it has failed and is the 1st test to fail, record the time
  if [[ "$?" -ne 0 ]] && [ "$failure_happened" = false ] ; then
    failure_happened=true
    fail_time="$(date +%s)"
    time_to_failure=$((fail_time - start_time))

    printf "Test Failed, time to first failure: $time_to_failure seconds\n" >> "$output"
  fi
  
  test_number=`expr $test_number + 1`

done < "$input"

if [ "$failure_happened" = false ] ; then
  printf "Success\n" >> "$output"
fi

exit 0